### ISSUE TITLE
Database models

### ISSUE THREAD

**Issue by Calvados0806** [19-20-1-PMi32/Sport-Betting-Trainer#2]
Implement models for database tables

**Comment by DthRazak** [comment]
As we make Web app now, do we need user authorization? 'Cause in this case need to implement User model.

**Comment by Calvados0806** [comment]
That's a good question, @DthRazak. It depends on will all users have access to our app functionality? Or only authenticated?

**Comment by DthRazak** [comment]
@Calvados0806 , I think only authenticated,  'cause we need to store bet history to show statistic.

**Comment by Calvados0806** [comment]
Ok, @DthRazak. Keep implementing this feature

**Comment by Calvados0806** [comment]
I'm closing this ticket
